// Lista fija de libros reales (uno por cada archivo EPUB disponible)
export const LIBROS_DATA = [
    {
        id: 'libro-1',
        titulo: 'El secreto del árbol',
        autor: 'María García',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+8',
        tematica: 'Aventura',
        genero: 'Narrativa',
        valores: ['Amistad', 'Valentía'],
        paginas: 120,
        descripcion: 'Una aventura emocionante que te llevará a lugares increíbles.',
        portada: 'https://placehold.co/300x450/FF6B6B/ffffff?text=El+secreto+del+arbol',
        epubFile: '/epubs/200994_ePub_YATA_ElSecretoDelArbol_ADN.epub',
        añoPublicacion: 2020,
        isbn: '978-84-10000-0',
        disponible: true
    },
    {
        id: 'libro-2',
        titulo: 'Los linces abandonados',
        autor: 'Juan Martínez',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+10',
        tematica: 'Medioambiente',
        genero: 'Narrativa',
        valores: ['Empatía', 'Respeto'],
        paginas: 145,
        descripcion: 'Descubre los secretos mejor guardados en esta historia fascinante.',
        portada: 'https://placehold.co/300x450/4ECDC4/ffffff?text=Los+linces',
        epubFile: '/epubs/200995_ePub_TOPEZ_LosLincesAbandonados_ADN.epub',
        añoPublicacion: 2021,
        isbn: '978-84-10001-1',
        disponible: true
    },
    {
        id: 'libro-3',
        titulo: 'Animaleza',
        autor: 'Carmen López',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+8',
        tematica: 'Medioambiente',
        genero: 'Narrativa',
        valores: ['Respeto', 'Creatividad'],
        paginas: 98,
        descripcion: 'Un viaje lleno de sorpresas y aprendizajes que no olvidarás.',
        portada: 'https://placehold.co/300x450/45B7D1/ffffff?text=Animaleza',
        epubFile: '/epubs/200996_ePub_Animaleza_ADR.epub',
        añoPublicacion: 2022,
        isbn: '978-84-10002-2',
        disponible: true
    },
    {
        id: 'libro-4',
        titulo: 'La escuela de gladiadores',
        autor: 'Pedro Sánchez',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+10',
        tematica: 'Aventura',
        genero: 'Narrativa',
        valores: ['Valentía', 'Perseverancia'],
        paginas: 160,
        descripcion: 'Sumérgete en un mundo de fantasía y magia sin límites.',
        portada: 'https://placehold.co/300x450/FFA07A/ffffff?text=Gladiadores',
        epubFile: '/epubs/200997 ADV_Escuela_gladiadores.epub',
        añoPublicacion: 2021,
        isbn: '978-84-10003-3',
        disponible: true
    },
    {
        id: 'libro-5',
        titulo: 'Llegendes de Roca Grossa',
        autor: 'Ana Fernández',
        editorial: 'Edelvives Comunidad Valenciana',
        idioma: 'Valenciano',
        edadRecomendada: '+8',
        tematica: 'Fantasía',
        genero: 'Narrativa',
        valores: ['Creatividad', 'Amistad'],
        paginas: 110,
        descripcion: 'Una historia conmovedora sobre la amistad y el valor.',
        portada: 'https://placehold.co/300x450/98D8C8/ffffff?text=Roca+Grossa',
        epubFile: '/epubs/208493_LLEGENDES_Roca_Grossa_Val.epub',
        añoPublicacion: 2023,
        isbn: '978-84-10004-4',
        disponible: true
    },
    {
        id: 'libro-6',
        titulo: 'Els talpins i els linxs abandonats',
        autor: 'Luis González',
        editorial: 'Edelvives Comunidad Valenciana',
        idioma: 'Valenciano',
        edadRecomendada: '+10',
        tematica: 'Medioambiente',
        genero: 'Narrativa',
        valores: ['Empatía', 'Responsabilidad'],
        paginas: 128,
        descripcion: 'Acompaña a los protagonistas en su increíble misión.',
        portada: 'https://placehold.co/300x450/F7DC6F/ffffff?text=Talpins',
        epubFile: '/epubs/208494_ADN_Talpis_linxs_abandonats_Val.epub',
        añoPublicacion: 2022,
        isbn: '978-84-10005-5',
        disponible: true
    },
    {
        id: 'libro-7',
        titulo: 'Mestratge salvatge',
        autor: 'Isabel Rodríguez',
        editorial: 'Edelvives Comunidad Valenciana',
        idioma: 'Valenciano',
        edadRecomendada: '+12',
        tematica: 'Aventura',
        genero: 'Narrativa',
        valores: ['Valentía', 'Perseverancia'],
        paginas: 175,
        descripcion: 'Un relato que te hará reír, llorar y soñar.',
        portada: 'https://placehold.co/300x450/FF6B6B/ffffff?text=Mestratge',
        epubFile: '/epubs/208495_ADR_Mestratge_salvatge_Val.epub',
        añoPublicacion: 2023,
        isbn: '978-84-10006-6',
        disponible: true
    },
    {
        id: 'libro-8',
        titulo: 'Carmen Conde',
        autor: 'Miguel Pérez',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+12',
        tematica: 'Sentimientos',
        genero: 'No ficción',
        valores: ['Honestidad', 'Creatividad'],
        paginas: 92,
        descripcion: 'Explora mundos desconocidos llenos de misterio.',
        portada: 'https://placehold.co/300x450/4ECDC4/ffffff?text=Carmen+Conde',
        epubFile: '/epubs/208829_ePub_Carmen_Conde.epub',
        añoPublicacion: 2020,
        isbn: '978-84-10007-7',
        disponible: true
    },
    {
        id: 'libro-9',
        titulo: 'Gwyneth',
        autor: 'Laura Gómez',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+10',
        tematica: 'Fantasía',
        genero: 'Narrativa',
        valores: ['Amistad', 'Valentía'],
        paginas: 142,
        descripcion: 'Una narración que inspira y motiva a ser mejor cada día.',
        portada: 'https://placehold.co/300x450/45B7D1/ffffff?text=Gwyneth',
        epubFile: '/epubs/208830_Gwyneth_ePub.epub',
        añoPublicacion: 2021,
        isbn: '978-84-10008-8',
        disponible: true
    },
    {
        id: 'libro-10',
        titulo: 'Verano en el asteroide',
        autor: 'Carlos Ruiz',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+10',
        tematica: 'Ciencia y Tecnología',
        genero: 'Narrativa',
        valores: ['Creatividad', 'Perseverancia'],
        paginas: 155,
        descripcion: 'Vive experiencias únicas a través de estas páginas.',
        portada: 'https://placehold.co/300x450/FFA07A/ffffff?text=Asteroide',
        epubFile: '/epubs/208831_Verano_asteroide_ePub.epub',
        añoPublicacion: 2022,
        isbn: '978-84-10009-9',
        disponible: true
    },
    {
        id: 'libro-11',
        titulo: 'Diez perritos',
        autor: 'Elena Díaz',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+6',
        tematica: 'Humor',
        genero: 'Narrativa',
        valores: ['Amistad', 'Empatía'],
        paginas: 65,
        descripcion: 'Una aventura emocionante que te llevará a lugares increíbles.',
        portada: 'https://placehold.co/300x450/98D8C8/ffffff?text=Diez+perritos',
        epubFile: '/epubs/209021_ePub_DiezPerritos_ADN.epub',
        añoPublicacion: 2020,
        isbn: '978-84-10010-0',
        disponible: true
    },
    {
        id: 'libro-12',
        titulo: 'Porcus',
        autor: 'José Moreno',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+8',
        tematica: 'Aventura',
        genero: 'Narrativa',
        valores: ['Valentía', 'Amistad'],
        paginas: 118,
        descripcion: 'Descubre los secretos mejor guardados en esta historia fascinante.',
        portada: 'https://placehold.co/300x450/F7DC6F/ffffff?text=Porcus',
        epubFile: '/epubs/209450_AL_Porcus_Epub.epub',
        añoPublicacion: 2023,
        isbn: '978-84-10011-1',
        disponible: true
    },
    {
        id: 'libro-13',
        titulo: 'Aurora siempre',
        autor: 'Marta Jiménez',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+10',
        tematica: 'Sentimientos',
        genero: 'Narrativa',
        valores: ['Empatía', 'Amistad'],
        paginas: 135,
        descripcion: 'Un viaje lleno de sorpresas y aprendizajes que no olvidarás.',
        portada: 'https://placehold.co/300x450/FF6B6B/ffffff?text=Aurora',
        epubFile: '/epubs/209451_Aurora_siempre_ePub.epub',
        añoPublicacion: 2021,
        isbn: '978-84-10012-2',
        disponible: true
    },
    {
        id: 'libro-14',
        titulo: 'Las margaritas',
        autor: 'Antonio Álvarez',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+8',
        tematica: 'Humor',
        genero: 'Narrativa',
        valores: ['Creatividad', 'Amistad'],
        paginas: 88,
        descripcion: 'Sumérgete en un mundo de fantasía y magia sin límites.',
        portada: 'https://placehold.co/300x450/4ECDC4/ffffff?text=Margaritas',
        epubFile: '/epubs/209452_Margaritas_ePub.epub',
        añoPublicacion: 2022,
        isbn: '978-84-10013-3',
        disponible: true
    },
    {
        id: 'libro-15',
        titulo: 'Benita Malva y el crimen',
        autor: 'Rosa Romero',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+10',
        tematica: 'Intriga',
        genero: 'Narrativa',
        valores: ['Honestidad', 'Perseverancia'],
        paginas: 165,
        descripcion: 'Una historia conmovedora sobre la amistad y el valor.',
        portada: 'https://placehold.co/300x450/45B7D1/ffffff?text=Benita+Malva',
        epubFile: '/epubs/209509 ADA_BenitaMalvaCrimen_EPUB.epub',
        añoPublicacion: 2023,
        isbn: '978-84-10014-4',
        disponible: true
    },
    {
        id: 'libro-16',
        titulo: 'Verán en Flamia',
        autor: 'Francisco Navarro',
        editorial: 'Ibaizabal',
        idioma: 'Gallego',
        edadRecomendada: '+8',
        tematica: 'Aventura',
        genero: 'Narrativa',
        valores: ['Valentía', 'Amistad'],
        paginas: 105,
        descripcion: 'Acompaña a los protagonistas en su increíble misión.',
        portada: 'https://placehold.co/300x450/FFA07A/ffffff?text=Flamia',
        epubFile: '/epubs/209510 ADA_Veran_Flamia.epub',
        añoPublicacion: 2021,
        isbn: '978-84-10015-5',
        disponible: true
    },
    {
        id: 'libro-17',
        titulo: 'La tercera super Minis',
        autor: 'Lucía Torres',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+10',
        tematica: 'Aventura',
        genero: 'Narrativa',
        valores: ['Valentía', 'Solidaridad'],
        paginas: 148,
        descripcion: 'Un relato que te hará reír, llorar y soñar.',
        portada: 'https://placehold.co/300x450/98D8C8/ffffff?text=Super+Minis',
        epubFile: '/epubs/209855  ADR_La terceraSuper_Minis_3_EPUB.epub',
        añoPublicacion: 2022,
        isbn: '978-84-10016-6',
        disponible: true
    },
    {
        id: 'libro-18',
        titulo: 'La casa del árbol',
        autor: 'Manuel Domínguez',
        editorial: 'Edelvives',
        idioma: 'Castellano',
        edadRecomendada: '+8',
        tematica: 'Aventura',
        genero: 'Narrativa',
        valores: ['Creatividad', 'Amistad'],
        paginas: 112,
        descripcion: 'Explora mundos desconocidos llenos de misterio.',
        portada: 'https://placehold.co/300x450/F7DC6F/ffffff?text=Casa+arbol',
        epubFile: '/epubs/217491_AL_Casa_arbol_Premio2024.epub',
        añoPublicacion: 2024,
        isbn: '978-84-10017-7',
        disponible: true
    },
    {
        id: 'libro-19',
        titulo: 'Nova adivinas',
        autor: 'Patricia Gil',
        editorial: 'Ibaizabal',
        idioma: 'Gallego',
        edadRecomendada: '+10',
        tematica: 'Intriga',
        genero: 'Narrativa',
        valores: ['Creatividad', 'Perseverancia'],
        paginas: 138,
        descripcion: 'Una narración que inspira y motiva a ser mejor cada día.',
        portada: 'https://placehold.co/300x450/FF6B6B/ffffff?text=Nova+adivinas',
        epubFile: '/epubs/218162_EPUB_ADR_Nova_adivinas_Gal.epub',
        añoPublicacion: 2024,
        isbn: '978-84-10018-8',
        disponible: true
    },
    {
        id: 'libro-20',
        titulo: 'A lúa das escusas',
        autor: 'Javier Vázquez',
        editorial: 'Ibaizabal',
        idioma: 'Gallego',
        edadRecomendada: '+8',
        tematica: 'Humor',
        genero: 'Narrativa',
        valores: ['Honestidad', 'Amistad'],
        paginas: 95,
        descripcion: 'Vive experiencias únicas a través de estas páginas.',
        portada: 'https://placehold.co/300x450/4ECDC4/ffffff?text=Lua+escusas',
        epubFile: '/epubs/218163_EPUB_ADN_Lua_Escusas_Gal.epub',
        añoPublicacion: 2024,
        isbn: '978-84-10019-9',
        disponible: true
    }
];
